# Python to Linux Web App on Azure
# Build your Python project and deploy it to Azure as a Linux Web App.
# Change python version to one thats appropriate for your application.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

name: Azure Pipelines
variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: 'eeac49b4-1894-49b3-91df-04c9be1f4656'

  # Web app name
  webAppName: 'project3'

  # Agent VM image name
  vmImageName: $(packer-temp)

  # Environment name
  environmentName: 'test'

  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)

  # Python version: 3.7
  pythonVersion: '3.7'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      vmImage: ubuntu-20.04
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'

    #- script: |
        #python -m venv antenv
        #source antenv/bin/activate
        #python -m pip install --upgrade pip
        #pip install setup
        #pip install -r requirements.txt
      #workingDirectory: $(System.DefaultWorkingDirectory)
      #displayName: "Install requirements"
    
    - task: InstallSSHKey@0
      displayName: 'Install an SSH key'
      inputs:
        knownHostsEntry: 'AAAAB3NzaC1yc2EAAAADAQABAAABgQDMXGz4sCr5PJEDPum/WuhZZ/Zsk2r9fgiuzbIJwaQh3VKZPvZwyUZ7G64UIP/sq76MjUsqnInB8cM/OBMwgy/3cXOhUJGcp43N4gh27KnW1FPinEIjDd5W7KxnpgNngaNo6M1eRHNa2a67pP8mEYIxkrlniyNA99YwC40ZGaOo7V82Hjd6AyTIIibtupId8+clQy4OaWSJ2VFLy9V852pnHPD2xaXnQ8m7cOsHz2rXnbCXTQ3M1XXHnRIM1P/yi1LddPtVHOuxi22c52E+O4dBsgRvvDCVbBqyyZP6SoRSzo7FF4VMLk1b6/lvDuJK8BDdXr3tYZZpBgd7K7rdxJELpYslk0abkYe96qdAYysERHDh+lJhMXn2f0WvE4Tkb36tiT0cfxwpMBHEJG1CBruIwO7ukwG+lG+CTHykZgXgaJ1Q/qK1728wo2BjkIW5FLAn2fknrs3y8DViZsRUDz0+Alt4iveaq4o+UEk/Tf8PbtzuLg4/XNoBneeav0AruJE= corneliuspchakabva@Corneliuss-Mini'
        sshPublicKey: '$(authorised_key)'
        sshKeySecureFile: 'authorised_keys'
    
    - task: DownloadSecureFile@1
      name: authorised_key
      displayName: 'Download Public Key'
      inputs:
        secureFile: 'authorised_key.pub'
  
    #- task: TerraformInstaller@0
      #displayName: 'Install Terraform 0.12.12'
      #inputs:
        #terraformVersion: '0.12.12'

    - task: TerraformTaskV1@0
      inputs:
        provider: 'azurerm'
        command: init
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environment/test'
        backendServiceArm: $(azureServiceConnectionId)
        backendAzureRmResourceGroupName: 'tstate-rg'
        backendAzureRmStorageAccountName: 'tstate2904'
        backendAzureRmContainerName: 'tstate-cn'
        backendAzureRmKey: 'terraform.tfstate'
      displayName: 'Initialize Terraform'

    - task: TerraformTaskV1@0
      inputs:
        command: validate
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environment/test' 
        backendAzureRmResourceGroupName: 'tstate-rg'
        backendAzureRmStorageAccountName: 'tstate2904'
      displayName: 'Run terraform validate'
    - task: TerraformTaskV1@0
      inputs:
        provider: 'azurerm'
        command: plan
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environment/test'
        commandOptions: '-var "public_key_path=$(udacity_public_key.secureFilePath)"'
        environmentServiceNameAzureRM: $(azureServiceConnectionId)
        #backendServiceArm: $(azureServiceConnectionId) 
      displayName: 'Tarraform Plan'
    - task: TerraformTaskV1@0
      
      inputs:
        provider: 'azurerm'
        command: Apply
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environment/test'
        commandOptions: '-var "public_key_path=$(udacity_public_key.secureFilePath)"'
        #environmentServiceNameAzureRM: $(azureServiceConnectionId) 
        backendServiceArm: $(azureServiceConnectionId)
      displayName: 'Tarraform Apply'  

    - task: ArchiveFiles@2
      displayName: 'Archive FakeRestAPI'
      inputs:
        rootFolderOrFile: 'jmeter/fakerestapi'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip
        #replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip
      displayName: 'Upload FakeRestAPI package'
      artifact: drop-fakerestapi

    - publish: selenium/login.py
      displayName: 'Upload UI Tests definition'
      artifact: drop_ui_tests


- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployfakeRestAPI
    pool:
      vmImage: ubuntu-20.04
    environment: $(TEST)
    strategy:
      runOnce:
        deploy:
          steps:

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
            displayName: 'Use Python version'

          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App : project3'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appName: $(webAppName)
              appType: webApp
              package: $(Pipeline.Workspace)/drop-fakerestapi/$(Build.BuildId)-fakerestapi.zip